### PR TITLE
check for mql before disposing of it

### PR DESCRIPTION
**Pull request by modosc**
this was causing errors in [react-responsive](https://github.com/contra/react-responsive)

### CODE REVIEW

**Comment by ncochard** [comment]
Thanks for the contribution.

**Comment by modosc** [comment]
thanks! can you do a release as well?

**Comment by ncochard** [comment]
Done. It's published.
Sorry I missed this. Thanks for fixing it.

**Comment by modosc** [comment]
~~thanks! i don't see it on npm yet, i'll keep checking.~~ there it is, thanks!

**Pull request merged**
